### ISSUE TITLE
Ruby 1.9 / 2.0 support

### ISSUE THREAD

**Issue by miah** [dbrady/tourbus#10]
"Ruby 1.8 and 2.0 have diverged so much that our britches have finally ripped. As of this writing (2013-03-18) I (dbrady) can get TourBus to build on 1.8.7 but not on ruby 1.9 or ruby 2.0. I think in the Very Near Future (which is hopefully much sooner than Real Soon Now) that Tourbus will go Ruby2-only and I’ll bump the version to 3.0 to keep people using 2.x from breaking hard."

**Comment by bbozo** [comment]
I use ruby 1.9.3 on https://github.com/bbozo/tourbus

**Comment by base10** [comment]
I'm trying @bbozo's fork with 1.9.3-p392 and getting failures.

<code>
/Users/nathan/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/Users/nathan/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/tourbus-2.0.2/bin/tourbus:8:in`<top (required)>': undefined method `symbolize_keys' for false:FalseClass (NoMethodError)
        from /Users/nathan/.rbenv/versions/1.9.3-p392/bin/tourbus:23:in`load'
        from /Users/nathan/.rbenv/versions/1.9.3-p392/bin/tourbus:23:in `<main>'
</code>

**Comment by bbozo** [comment]
@base10, I was using 1.9.3-p286, but tested now with p392 too and no exception for me

last line of this code is generating the exception:

``` ruby
  # load config file, we'll use these as defaults
  config_file = ["./tourbus.yml", "./tours/tourbus.yml", "./config/tourbus.yml", "~/tourbus.yml"].map {|p| File.expand_path(p)}.find {|p| File.exists? p}
  config = config_file ? YAML::load_file(config_file).symbolize_keys : {}
```

a problem with the config file or yml library?

**Comment by base10** [comment]
@bbozo Sure enough. Not having a tourbus.yml was the issue.
