### ISSUE TITLE
Undefined method `sub' on Ruby 1.9.2-p290

### ISSUE THREAD

**Issue by emachnic** [dbrady/tourbus#2]
I've only been able to get tourbus to run on 1.8.7. When I try to run the tours on 1.9.2 I get the following error:

```
/Users/evan/.rvm/gems/ruby-1.9.2-p290@tourbus/gems/tourbus-2.0.1/lib/tourist.rb:79:in `block in tours': undefined method `sub' for :tour_projects:Symbol (NoMethodError)
```

Here is my project_test.rb file:

```
class ProjectTest < Tourist
  def tour_projects
    visit "http://localhost:3000/projects"
    assert_contain 'Listing projects'
  end
end
```

**Comment by dbrady** [comment]
Hrrm, I'll look into this as I am able. I notice that linecache can't even build on 1.9.2-p290 so we may be off the reservation altogether here.

**Comment by seryl** [comment]
Have a pull request to handle this.

**Comment by DoppioJP** [comment]
In `tourbus` gem v 2.0.1 method `tours` has this problem. Here is the code from gem:

``` ruby
  # Returns list of tours this tourist knows about. (Meant to be run on a subclass
  # instance; returns the list of tours available).
  def tours
    methods.grep(/^tour_/).map {|m| m.sub(/^tour_/,'')}
  end
```

To compare the current code on GitHub is:

``` ruby
  # Returns list of tours this tourist knows about. (Meant to be run on a subclass
  # instance; returns the list of tours available).
  def tours
    methods.map(&:to_s).grep(/^tour_/).map {|m| m.sub(/^tour_/,'')}
  end
```

where the symbols in `methods` are converted into string already.

Do you recommend getting this gem from source and building it myself? I am currently using it from https://rubygems.org/gems/tourbus

**Comment by keithmgould** [comment]
Hiya, I ran into this problem also, and fixed it, though it seems its fixed in the codebase.  Just a reminder that your published gem does not seem to reflect the change that DoppioJP mentioned above.

Keith
